# Generated by Django 4.0.1 on 2022-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='task_date',
            field=models.DateField(default='2022-08-30 22:14:01.766103', verbose_name='Дата'),
        ),
    ]
